### ISSUE TITLE
AttributeError: 'drive_remote' object has no attribute 'source_path_id'

### ISSUE THREAD

**Issue by mtnjustme** [endevrr/AutoRclone-Rewrite#1]
elif unencrypted_remote.source_path_id:
                                remote_template += '{} = {}\n\n'.format('source_path_id', unencrypted_remote.source_path_id)

there is no source_path_id in unencrypted_remote, what did u mean by that?

**Comment by williamjohnstone** [comment]
Sorry for the incredibly late reply, I've not been looking at this repo or Github notifications, I actually had issues with this and just couldn't wrap my head around it, thanks for point it out

**Comment by williamjohnstone** [comment]
Working on this now
